// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';

const SUPABASE_URL = "https://yrixrsthjntarzcyiryg.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InlyaXhyc3Roam50YXJ6Y3lpcnlnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTIwMjM3MTgsImV4cCI6MjA2NzU5OTcxOH0.YGflIBoKEf8nDK6WJwwcZxItwWg2iVA81mtzASH2UNE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);